### ISSUE TITLE
Please add an open source license

### ISSUE THREAD

**Issue by RudyD** [mallibone/XamarinAddressPosition#1]
I saw your blog post (link below) and enjoyed seeing your Xamarin Forms Maps example.
https://mallibone.com/post/xamarin-maps-addresses-geocoords

Unfortunately, I can't use your code without an open source license. Would you mind please adding one?

MIT is preferable, but any other open source one will be welcome.

Thanks

**Comment by mallibone** [comment]
Hey @RudyD sure thing, added the license.

**Comment by RudyD** [comment]
Thanks a bunch @mallibone ! Stay safe.
